plugins {
    id "org.jetbrains.kotlin.jvm" version "2.1.10"
}

kotlin {
    jvmToolchain(17)
}
dependencies {
    implementation project(':common')

    compileOnly "org.jetbrains.kotlin:kotlin-stdlib:2.1.10"

    compileOnly "net.dmulloy2:ProtocolLib:5.4.0"
    compileOnly("io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT")
    compileOnly("org.joml:joml:1.10.8")
}