name: TestPlugin
version: 1.0.0
description: Test plugin for RavinAPI
author: RAVINGAR

api-version: 1.18

main: com.ravingarinc.test.TestPlugin

depend: [ ProtocolLib ]

commands:
  test:
    description: Test command
    usage: '/test'